[book]
authors      = ["Miden contributors"]
description  = "Manual for the Miden Faucet application"
language     = "en"
title        = "The Miden Faucet"

[output.html]
git-repository-url = "https://github.com/0xMiden/miden-faucet"
