name: Cargo Publish (dry-run)

permissions:
  contents: read

on:
  push:
    branches: [main, next, tomasarrachea-cargo-publish-workflow]

jobs:
  cargo-publish-dry-run:
    name: Cargo publish dry-run
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == '0xMiden' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update Rust toolchain
        run: |
          rustup update --no-self-update
      - name: Dry-run publish to crates.io
        run: cargo publish --workspace --dry-run
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
